// A2 bozuk entry'lerini gerçekten temizle ve çevir.
const fs = require('node:fs');
const path = require('node:path');

// idx → { de, tr } eşlemesi (orijinal a2.json içindeki array index)
const F = {
  0:   ["das Guerilla-Stricken", "gerilla örgüsü (sokakta örgü asma sanatı)"],
  5:   ["das Backgammon", "tavla (oyun)"],
  7:   ["ganz", "tamamen, oldukça"],
  8:   ["schön", "güzel; oldukça"],
  13:  ["fit", "formda, zinde"],
  19:  ["schenken", "hediye etmek"],
  39:  ["manch-", "bazı (kimseler)"],
  40:  ["bestimmt", "kesinlikle; eminim"],
  43:  ["das Geburtstagsgeschenk, -e", "doğum günü hediyesi"],
  49:  ["surfen", "sörf yapmak"],
  52:  ["also", "yani, demek ki"],
  63:  ["finden", "bulmak, düşünmek"],
  64:  ["klettern", "tırmanmak"],
  70:  ["probieren", "denemek"],
  72:  ["gefährlich", "tehlikeli"],
  73:  ["passieren", "olmak, gerçekleşmek"],
  80:  ["fast", "neredeyse"],
  84:  ["üben", "alıştırma yapmak, çalışmak"],
  85:  ["das Konzert, -e", "konser"],
  105: ["das Kulturprogramm, -e", "kültür programı"],
  109: ["sportlich", "sportif, atletik"],
  115: ["das Improtheater", "doğaçlama tiyatro"],
  116: ["total", "tamamen, gerçekten"],
  117: ["spannend", "heyecan verici"],
  122: ["das Mitglied, -er", "üye"],
  134: ["die Eröffnung, -en", "açılış"],
  141: ["neben", "yanında"],
  144: ["hoffen", "umut etmek"],
  147: ["übrigens", "bu arada"],
  149: ["unsympathisch", "sevimsiz, antipatik"],
  153: ["die Ehrlichkeit", "dürüstlük"],
  157: ["versprechen", "söz vermek"],
  158: ["zuhören", "dinlemek"],
  159: ["stimmen", "doğru olmak"],
  171: ["positiv", "olumlu"],
  173: ["negativ", "olumsuz"],
  177: ["unsportlich", "sportif olmayan"],
  179: ["kündigen", "istifa etmek, fesh etmek"],
  181: ["ziehen", "taşınmak (buraya: yer değiştirmek)"],
  183: ["die Pension, -en", "pansiyon, küçük otel"],
  191: ["genießen", "tadını çıkarmak"],
  192: ["nutzen", "kullanmak"],
  195: ["das Abendessen, -", "akşam yemeği"],
  196: ["segeln", "yelken açmak, yelkenlik yapmak"],
  197: ["inklusive", "dahil"],
  206: ["lecker", "lezzetli"],
  208: ["ganz", "oldukça"],
  223: ["der/die Psychologe, -n / Psychologin, -nen", "psikolog"],
  224: ["arbeitslos", "işsiz"],
  225: ["der/die Tauchlehrer, - / Tauchlehrerin, -nen", "dalış eğitmeni"],
  228: ["der/die Dritte, -n", "üçüncüsü (üçüncü olmak)"],
  230: ["kalt", "soğuk"],
  231: ["warm", "sıcak, ılık"],
  232: ["sonst", "yoksa, aksi halde"],
  237: ["berühmt", "ünlü"],
  238: ["der/die Kleine, -n", "küçük (çocuk)"],
  239: ["verlieren", "kaybetmek"],
  253: ["okay", "tamam, peki"],
  288: ["der Burger, -", "burger, hamburger"],
  292: ["asiatisch", "Asyalı, Asya'ya ait"],
  300: ["wählen", "seçmek"],
  302: ["danach", "sonra, ondan sonra"],
  312: ["das Mineralwasser, -", "maden suyu"],
  315: ["das Huhn, Hühner", "tavuk"],
  316: ["der Eisbecher, -", "dondurma kupası"],
  317: ["das Tiramisu, -", "tiramisu"],
  319: ["zu", "için, -e"],
  322: ["vegetarisch", "vejetaryen"],
  325: ["aufräumen", "toparlamak, düzenlemek"],
  337: ["hinzugeben", "eklemek (yemeğe)"],
  338: ["verrühren", "karıştırmak"],
  339: ["wenden", "çevirmek (yemeği)"],
  340: ["schneiden", "kesmek, doğramak"],
  358: ["stehen", "yazılı olmak (burada: yazıyor)"],
  360: ["niemand", "hiç kimse"],
  362: ["anschalten", "açmak, çalıştırmak"],
  376: ["die Magenschmerzen", "mide ağrısı"],
  380: ["früher", "eskiden"],
  381: ["der Döner, -", "döner"],
  388: ["die Uni, -s", "üniversite (kısaca)"],
  389: ["in Ruhe", "huzur içinde, rahatça"],
  396: ["der Löffel, -", "kaşık"],
  417: ["das Anmeldegespräch, -e", "kayıt görüşmesi"],
  418: ["das Sekretariat, -e", "sekreterlik"],
  421: ["mittwochs", "çarşamba günleri"],
  424: ["der Schüleraustausch, -e", "öğrenci değişimi"],
  426: ["der/die Helfer, - / Helferin, -nen", "yardımcı"],
  435: ["entscheiden", "karar vermek"],
  444: ["drankommen", "sıra ona gelmek"],
  466: ["der/die Übersetzer, - / Übersetzerin, -nen", "tercüman"],
  470: ["stressen", "strese sokmak"],
  471: ["ziemlich", "oldukça, epeyce"],
  472: ["vorbei", "geçmiş, bitmiş"],
  486: ["prima", "harika, mükemmel"],
  491: ["der/die Tänzer, - / Tänzerin, -nen", "dansçı"],
  500: ["aufregend", "heyecan verici"],
  501: ["zuerst", "önce, ilk"],
  504: ["furchtbar", "berbat, korkunç"],
  505: ["schneien", "kar yağmak"],
  507: ["nervös", "gergin, sinirli"],
  521: ["das Mädchen, -", "kız"],
  524: ["weiter", "devam (daha ileri)"],
  525: ["die Medizin", "tıp"],
  528: ["die Bewerbung, -en", "başvuru"],
  542: ["sitzenbleiben", "sınıfta kalmak"],
  550: ["die Kenntnis, -se", "bilgi, beceri"],
  551: ["die Tätigkeit, -en", "faaliyet, iş"],
  552: ["die Terminkoordination", "randevu koordinasyonu"],
  556: ["die Mittlere Reife", "orta öğretim diploması"],
  567: ["die Schulbildung", "okul eğitimi"],
  570: ["die/das/der Au-pair, -s", "au-pair (yabancı ailede çocuk bakan)"],
  571: ["die Sprachschule, -n", "dil okulu"],
  576: ["losgehen", "başlamak, yola çıkmak"],
  577: ["umsteigen", "aktarma yapmak"],
  585: ["die Lebenserfahrung", "yaşam tecrübesi"],
  586: ["ideal", "ideal, mükemmel"],
  589: ["die Möglichkeit, -en", "imkân, fırsat"],
  590: ["zu Ende", "sonuna, bittiğinde"],
  591: ["traurig", "üzgün"],
  597: ["mitarbeiten", "birlikte çalışmak"],
  598: ["zurückfliegen", "geri uçmak"],
  601: ["du", "sen"],
  603: ["betreuen", "ilgilenmek, bakmak"],
  607: ["der Vorteil, -e", "avantaj, fayda"],
  611: ["eventuell", "belki, muhtemelen"],
  615: ["das Taschengeld", "harçlık"],
  631: ["reichhaltig", "zengin, bol çeşit"],
  648: ["anreisen", "varmak (yolculukla)"],
  654: ["gegen", "civarında, yaklaşık"],
  655: ["die Übernachtung, -en", "konaklama, geceleme"],
  657: ["ausfüllen", "doldurmak (form)"],
  // Devamı geliyor
};

// 435 entry için manuel sözlük — kalan kısım
Object.assign(F, {
  662: ["tragen", "taşımak"],
  665: ["die Pizzeria, Pizzerien", "pizzacı"],
  670: ["vielleicht", "belki"],
  671: ["der Verkehrsverbund", "ulaşım birliği"],
  690: ["der Schlafplatz, Schlafplätze", "uyku yeri"],
  691: ["absagen", "iptal etmek"],
  693: ["wunderschön", "muhteşem, harika"],
  694: ["zurückkommen", "geri dönmek"],
  700: ["vermieten", "kiraya vermek"],
  701: ["das Erdgeschoss", "zemin kat"],
  709: ["die Mitte", "orta, merkez"],
  711: ["gehören", "ait olmak"],
  712: ["danke schön", "çok teşekkürler"],
  717: ["die Spielsachen", "oyuncaklar"],
  722: ["spazieren gehen", "gezintiye çıkmak"],
  727: ["zu viert", "dördümüz, dört kişi"],
  728: ["die Lampe, -n", "lamba"],
  732: ["füttern", "beslemek"],
  734: ["der Biomüll", "organik atık"],
  735: ["das Licht, -er", "ışık"],
  741: ["mitfeiern", "birlikte kutlamak"],
  742: ["ausschalten", "kapatmak (cihaz)"],
  749: ["herzliche Grüße", "selamlar, en içten dileklerle"],
  752: ["der Wochentag, -e", "haftanın günü"],
  755: ["das Mehrgenerationenhaus", "çok kuşaklı ev"],
  758: ["vorbeikommen", "uğramak"],
  759: ["weitersagen", "iletmek, başkalarına söylemek"],
  766: ["der/die Physiotherapeut, -en / Physiotherapeutin, -nen", "fizyoterapist"],
  768: ["zumachen", "kapatmak"],
  771: ["vor allem", "özellikle, her şeyden önce"],
  775: ["die Ordnung", "düzen, tertiplik"],
  776: ["offen", "açık, içten"],
  777: ["kompliziert", "karmaşık"],
  778: ["ordentlich", "düzenli, derli toplu"],
  779: ["die Sauberkeit", "temizlik"],
  787: ["das Raw Food", "çiğ besin"],
  789: ["erwärmen", "ısıtmak"],
  791: ["paläo", "paleo (beslenme)"],
  792: ["das Getreide, -", "tahıl"],
  794: ["gebacken", "fırınlanmış, pişmiş"],
  799: ["selten", "nadiren"],
  801: ["wehtun", "acı vermek"],
  809: ["usw.", "vb. (ve saire)"],
  810: ["fett", "yağlı"],
  813: ["das Besondere", "özel olan"],
  819: ["eher", "daha çok, ziyade"],
  823: ["das Telefax, -e", "faks"],
  833: ["leihen", "ödünç almak"],
  834: ["der/die Spieler, - / Spielerin, -nen", "oyuncu"],
  837: ["die Ermäßigung, -en", "indirim"],
  839: ["der/die Tanzpartner, - / Tanzpartnerin, -nen", "dans partneri"],
  846: ["abstellen", "park etmek, koymak"],
  852: ["klappen", "olmak, denk gelmek"],
  854: ["der Wald, Wälder", "orman"],
  858: ["merken", "fark etmek, hatırlamak"],
  861: ["sauer", "kızgın, sinirli"],
  863: ["stressig", "stresli, yorucu"],
  872: ["übrig", "kalan, artan"],
  874: ["der Arbeitsalltag", "iş günü, çalışma rutini"],
  878: ["kommunizieren", "iletişim kurmak"],
  879: ["die Kompetenz, -en", "yetkinlik, beceri"],
  883: ["rechnen", "hesap yapmak"],
  885: ["kulturell", "kültürel"],
  886: ["reagieren", "tepki vermek"],
  889: ["verschieben", "ertelemek"],
  890: ["deshalb", "bu yüzden"],
  895: ["verbinden", "bağlamak (telefon)"],
  900: ["Englisch", "İngilizce"],
  904: ["versuchen", "denemek, çalışmak"],
  907: ["der Dialekt, -e", "lehçe, ağız"],
  910: ["schön", "güzel; oldukça"],
  912: ["chillen", "rahatlamak, gevşemek"],
  914: ["unterrichten", "ders vermek"],
  916: ["der Strudel, -", "strudel (rulo hamur işi)"],
  918: ["am meisten", "en çok"],
  920: ["schwierig", "zor"],
  925: ["aussprechen", "telaffuz etmek"],
  928: ["die Info, -s", "bilgi (kısaca)"],
  933: ["seit kurzem", "kısa süredir, son zamanlarda"],
  946: ["das Spaßbad, Spaßbäder", "eğlence havuzu"],
  949: ["hinfahren", "oraya gitmek"],
  952: ["die Verwandtschaft", "akrabalar"],
  954: ["die Nichte, -n", "kız yeğen"],
  956: ["der Schwager", "kayınbirader, eniştele"],
  957: ["der/die Enkel, - / Enkelin, -nen", "torun"],
  961: ["der/die Verwandte, -n", "akraba"],
  962: ["der/die Urenkel, - / Urenkelin, -nen", "torun çocuğu"],
  967: ["berichten", "haber vermek, bildirmek"],
  969: ["irgendwie", "bir şekilde"],
  973: ["losmüssen", "gitmek zorunda olmak"],
  977: ["das Firmenjubiläum", "şirket yıldönümü"],
  979: ["die Zusammenarbeit", "işbirliği"],
  981: ["sich verabschieden", "vedalaşmak"],
  984: ["wiedersehen", "yeniden görüşmek"],
  988: ["küssen", "öpmek"],
  989: ["gespannt", "meraklı, sabırsız"],
  991: ["spontan", "doğal, anlık"],
  995: ["andere", "başkaları, diğerleri"],
  997: ["unkompliziert", "rahat, sorunsuz"],
  999: ["froh", "mutlu, sevinçli"],
  1003: ["der Vorschlag, Vorschläge", "öneri, teklif"],
  1006: ["verärgert", "kızgın, sinirli"],
  1009: ["erstaunt", "şaşırmış"],
  1010: ["häufig", "sık sık"],
  1014: ["einzeln", "tek tek, ayrı ayrı"],
  1018: ["tief", "derin"],
  1020: ["betont", "vurgulu"],
  1023: ["präzise", "kesin, net"],
  1028: ["verliebt", "âşık"],
  1034: ["drin", "içeride"],
  1037: ["von ... bis", "-den -e kadar"],
  1041: ["fix", "sabit, belirli"],
  1043: ["technisch", "teknik"],
  1044: ["der Lieferrhythmus", "teslimat sıklığı"],
  1048: ["die Kündigung, -en", "fesih, iptal"],
  1052: ["schriftlich", "yazılı olarak"],
  1054: ["der Zeitpunkt, -e", "zaman, an"],
  1059: ["der Spiegel, -", "ayna"],
  1063: ["der Sessel, -", "koltuk"],
  1064: ["der Stiefel, -", "çizme"],
  1068: ["selber", "kendi (başına)"],
  1075: ["der/die Anbieter, - / Anbieterin, -nen", "satıcı, sunucu"],
  1080: ["der/die Tauschpartner, - / Tauschpartnerin, -nen", "takas ortağı"],
  1083: ["der Tausch", "takas, değişim"],
  1088: ["weg", "uzakta, gitmiş"],
  1090: ["die Tauschbörse, -n", "takas platformu"],
  1095: ["bestimmt", "belirli, özel"],
  1107: ["vorlesen", "sesli okumak"],
  1109: ["der Tierschutz", "hayvan koruma"],
  1112: ["die Werkstatt, Werkstätten", "atölye"],
  1115: ["geistig", "zihinsel"],
  1116: ["körperlich", "bedensel, fiziksel"],
  1119: ["die Feuerwehr, -en", "itfaiye"],
  1124: ["hochhelfen", "ayağa kalkmasına yardım etmek"],
  1126: ["lieb", "tatlı, sevecen"],
  1131: ["der Durchschnitt, -e", "ortalama"],
  1133: ["der Umweltbereich, -e", "çevre alanı"],
  1140: ["wegwerfen", "atmak (çöpe)"],
  1144: ["weiterdürfen", "devam etme izni"],
  1146: ["ernst", "ciddi"],
  1150: ["wozu", "ne için, neden"],
  1156: ["um", "için (-mek için)"],
  1158: ["kostenfrei", "ücretsiz"],
  1162: ["eng", "dar, sıkı"],
  1163: ["atmen", "nefes almak"],
  1167: ["bluten", "kanamak"],
  1170: ["der Rücken, -", "sırt"],
  1173: ["erlauben", "izin vermek"],
  1183: ["der Flüchtling, -e", "mülteci"],
  1185: ["der/die Migrant, -en / Migrantin, -nen", "göçmen"],
  1187: ["unterstützen", "desteklemek"],
  1189: ["das Sprachspiel, -e", "dil oyunu"],
  1195: ["die Bescherung", "hediye dağıtımı (Noel'de)"],
  1196: ["heißen", "anlamına gelmek"],
  1197: ["auspacken", "açmak (hediye)"],
  1200: ["der Weihnachtsmann", "Noel Baba"],
  1207: ["die Weihnachtsgans", "Noel kazı"],
  1215: ["der Osterhase, -n", "Paskalya tavşanı"],
  1218: ["das Ostern, -", "Paskalya"],
  1230: ["der Würstchenstand", "sosis büfesi"],
  1232: ["minus", "eksi"],
  1237: ["eine Hand voll", "bir avuç"],
  1238: ["umsonst", "bedava, ücretsiz"],
  1243: ["mitsingen", "birlikte söylemek"],
  1249: ["freitags", "cuma günleri"],
  1250: ["unter", "süresince, esnasında"],
  1256: ["der Ersatzschlüssel, -", "yedek anahtar"],
  1261: ["blöd", "aptal, salakça"],
  1268: ["garantieren", "garanti etmek"],
  1271: ["erkennen", "tanımak, fark etmek"],
  1275: ["woanders", "başka bir yerde"],
  1279: ["sich kennenlernen", "birbirini tanımak"],
  1286: ["der Wochenplan, Wochenpläne", "haftalık plan"],
  1290: ["achten", "dikkat etmek"],
  1295: ["der/die Kinderpsychologe, -n / Kinderpsychologin, -nen", "çocuk psikoloğu"],
  1297: ["das Schlafproblem, -e", "uyku problemi"],
  1300: ["psychologisch", "psikolojik"],
  1303: ["die Krankmeldung, -en", "hastalık raporu"],
  1306: ["übernächst-", "sonraki sonraki"],
  1308: ["durchschnittlich", "ortalama olarak"],
  1311: ["getrennt", "ayrı, ayrı ayrı"],
  1313: ["voneinander", "birbirinden"],
  1315: ["klassisch", "klasik"],
  1317: ["weitergehen", "devam etmek"],
  1321: ["der Krankheitstag, -e", "hastalık günü"],
  1323: ["steigen", "yükselmek, artmak"],
  1328: ["vorletzt-", "bir önceki, geçen geçen"],
  1331: ["die Infrastruktur, -en", "altyapı"],
  1333: ["vermuten", "tahmin etmek, sanmak"],
  1338: ["der/die Senner, - / Sennerin, -nen", "yayla çobanı"],
  1343: ["jede Menge", "bir sürü, bol miktarda"],
  1348: ["ausgehen", "dışarı çıkmak"],
  1352: ["begleiten", "eşlik etmek"],
  1356: ["die Yogastunde, -n", "yoga dersi"],
  1360: ["der/die Surflehrer, - / Surflehrerin, -nen", "sörf eğitmeni"],
  1366: ["neblig", "sisli"],
  1369: ["stürzen", "düşmek"],
  1373: ["der Tagesablauf, Tagesabläufe", "günlük plan"],
  1378: ["der Rand, Ränder", "kenar"],
  1383: ["mitliefern", "birlikte teslim etmek"],
  1390: ["professionell", "profesyonel"],
  1395: ["zuzüglich", "ek olarak, artı"],
  1398: ["der Mietwagen, -", "kiralık araba"],
  1402: ["vermitteln", "aracılık etmek"],
  1406: ["hersetzen", "buraya oturmak"],
  1408: ["hinstellen", "koymak (bir yere)"],
  1411: ["weitermachen", "devam etmek"],
  1414: ["vorbeibringen", "uğrayıp getirmek"],
  1416: ["einräumen", "yerleştirmek, dolaba koymak"],
  1419: ["rangehen", "(telefona) cevap vermek"],
  1422: ["telefonisch", "telefonla"],
  1425: ["folgend-", "aşağıdaki, sonraki"],
  1431: ["die Wegbeschreibung, -en", "yol tarifi"],
  1435: ["ob", "-ip -ip"],
  1437: ["nachsehen", "bakmak, kontrol etmek"],
  1441: ["der Taschendiebstahl", "yankesicilik"],
  1444: ["kontrollieren", "denetlemek, kontrol etmek"],
  1447: ["die Gefahr, -en", "tehlike"],
  1450: ["der/die Polizeisprecher, - / Polizeisprecherin, -nen", "polis sözcüsü"],
  1453: ["stehlen", "çalmak"],
  1457: ["dabeihaben", "yanında bulundurmak"],
  1460: ["der/die Zahnarzt, Zahnärzte / Zahnärztin, -nen", "diş hekimi"],
  1463: ["lösen", "çözmek"],
  1466: ["das Fundamt, Fundämter", "kayıp eşya bürosu"],
  1469: ["variieren", "değişiklik göstermek"],
  1472: ["eilig", "acele, aceleci"],
  1475: ["fallen", "düşmek"],
  1478: ["das Ausweisdokument, -e", "kimlik belgesi"],
  1481: ["sorgen", "ilgilenmek, sağlamak"],
  1484: ["die Überweisung, -en", "havale, banka transferi"],
  1487: ["die Datensicherheit", "veri güvenliği"],
  1497: ["der Treffpunkt, -e", "buluşma noktası"],
  1500: ["im Anschluss", "ardından, sonrasında"],
  1503: ["herumliegen", "etrafta durmak"],
  1506: ["noch nie", "hiç (şimdiye kadar)"],
  1509: ["das Stadtgebiet, -e", "şehir alanı"],
  1512: ["der/die Bürger, - / Bürgerin, -nen", "vatandaş"],
  1515: ["der/die Leser, - / Leserin, -nen", "okur"],
  1518: ["der/die Maler, - / Malerin, -nen", "ressam"],
  1521: ["der/die Organisator, -en / Organisatorin, -nen", "organizatör"],
  1524: ["enttäuscht", "hayal kırıklığına uğramış"],
  1527: ["näher", "daha yakın, daha ayrıntılı"],
  1530: ["die Planung, -en", "planlama"],
  1533: ["ernten", "hasat etmek"],
  1536: ["das Beste", "en iyisi"],
  1539: ["inzwischen", "bu arada"],
  1542: ["raufgehen", "yukarı çıkmak"],
  1545: ["zeichnen", "çizmek"],
  1548: ["nachschauen", "bakmak"],
  1551: ["etwas Ähnliches", "benzer bir şey"],
  1554: ["versichert", "sigortalı"],
  1557: ["die Registrierung, -en", "kayıt"],
  1560: ["jederzeit", "her zaman"],
  1563: ["ausleihen", "ödünç almak"],
  1566: ["campen", "kamp yapmak"],
  1569: ["sowieso", "zaten, nasıl olsa"],
  1572: ["verlängern", "uzatmak"],
  1581: ["erfolgreich", "başarılı"],
  1584: ["weiter-", "ileri, daha"],
  1587: ["präsentieren", "sunmak, takdim etmek"],
  1590: ["ziehen", "taşınmak"],
  1593: ["wahrmachen", "gerçeğe dönüştürmek"],
  1596: ["überschätzen", "abartmak, fazla değer vermek"],
  1599: ["kritisch", "eleştirel"],
  1602: ["sowas von", "öyle ki, fevkalade"],
  1605: ["das Spiegelbild, -er", "ayna görüntüsü"],
  1608: ["sich anfühlen", "hissedilmek, hissi olmak"],
  1611: ["der Teenager, -", "genç, ergen"],
  1615: ["aufhören", "durdurmak, son vermek"],
  1618: ["das Radio", "radyo"],
  1621: ["englisch", "İngilizce"],
  1624: ["die Spielekonsole, -n", "oyun konsolu"],
  1627: ["der/die Gamer, - / Gamerin, -nen", "oyuncu (video oyunu)"],
  1630: ["der Follower, -", "takipçi"],
  1633: ["der/die Hörer, - / Hörerin, -nen", "dinleyici"],
  1636: ["ausverkauft", "satıldı, tükendi"],
  1645: ["das Ausbildungsjahr, -e", "eğitim yılı"],
  1649: ["beraten", "danışmanlık etmek"],
  1652: ["die Verantwortung, -en", "sorumluluk"],
  1655: ["der/die Chemielaborant, -en / Chemielaborantin, -nen", "kimya laboranı"],
  1658: ["zuschicken", "göndermek"],
  1661: ["per Post", "posta yoluyla"],
  1664: ["der/die Spanier, - / Spanierin, -nen", "İspanyol"],
  1667: ["der Arbeitsvertrag, Arbeitsverträge", "iş sözleşmesi"],
  1670: ["der/die Kanadier, - / Kanadierin, -nen", "Kanadalı"],
  1673: ["von ... aus", "-den (bir yerden)"],
  1676: ["der Arbeitsweg, -e", "işe gidiş yolu"],
  1679: ["der Hort, -e", "okul sonrası bakım"],
  1682: ["die Kindertagesstätte, -n", "çocuk kreşi"],
  2360: ["tolerant", "hoşgörülü"],
  2363: ["türkisch", "Türkçe"],
  2366: ["beschützen", "korumak"],
  2369: ["der/die Informatiker, - / Informatikerin, -nen", "bilgisayar uzmanı"],
  2372: ["der/die Japaner, - / Japanerin, -nen", "Japon (kişi)"],
  2375: ["aufwachsen", "büyümek (çocukluktan)"],
  2378: ["aufstellen", "dikmek, kurmak"],
  2381: ["deutschsprachig", "Almanca konuşan"],
  2384: ["der/die Schweizer, - / Schweizerin, -nen", "İsviçreli"],
  2387: ["hinausfahren", "(denize, açığa) çıkmak"],
  2390: ["anmachen", "açmak (ışık vb)"],
  2393: ["der Discounter, -", "indirim marketi"],
  2396: ["korrigieren", "düzeltmek"],
  2399: ["das Kopfkino", "hayal kurma, kafadaki film"],
  2402: ["der Eiertanz, Eiertänze", "yumurta üstünde yürümek (deyim)"],
});

// Bozuk olup F'de olmayan idx'leri tespit edip otomatik temizle
const a2 = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'data', 'a2.json'), 'utf8'));
const badIdx = require('./a2_bad_idx.json').map(x => x.idx);

let fixed = 0, autoCleaned = 0, stillBad = 0;
for (const idx of badIdx) {
  if (F[idx]) {
    a2[idx].de = F[idx][0];
    a2[idx].tr = F[idx][1];
    // ex ve ex_tr'yi sıfırla (genelde bozuk)
    delete a2[idx].ex;
    delete a2[idx].ex_tr;
    fixed++;
  } else {
    // Otomatik temizleme: ilk Almanca segmentini al
    const de = a2[idx].de || '';
    const tr = a2[idx].tr || '';
    // de'den ilk segmentini al
    let cleanDe = de;
    // "kelime İngilizce_anlam ..." kalıbında ilk parçayı al
    const m = de.match(/^((?:der\/die\s+)?(?:der|die|das)?\s*[A-ZÄÖÜa-zäöüß][\wäöüßÄÖÜ-]*(?:\s*,\s*-?[\wäöüß-]+)?)\s+([a-z])/);
    if (m && m[2].toLowerCase() !== m[2]) cleanDe = m[1].trim();
    else if (de.length > 50) cleanDe = de.split(/\s{2,}|\s(?=[A-Z][a-z]{3,})/)[0].trim();
    a2[idx].de = cleanDe || de;
    // tr çok uzunsa kes
    if (tr.length > 60) a2[idx].tr = '';
    delete a2[idx].ex;
    delete a2[idx].ex_tr;
    autoCleaned++;
    if (!a2[idx].tr) stillBad++;
  }
}

fs.writeFileSync(path.join(__dirname, '..', 'data', 'a2.json'), JSON.stringify(a2, null, 0).replace(/},{/g, '},\n{') + '\n');
console.log(`Manuel düzeltilen: ${fixed}`);
console.log(`Otomatik temizlenen: ${autoCleaned}`);
console.log(`Hâlâ tr eksik: ${stillBad}`);
console.log(`Toplam A2 kelime: ${a2.length}`);
